services:
  zookeeper:
    image: bitnami/zookeeper:latest  # ใช้ภาพ Docker ของ Zookeeper ที่ใหม่กว่า
    ports:
      - "2181:2181"

  kafka1:
    image: bitnami/kafka:latest  # ใช้ภาพ Docker ของ Kafka ที่ใหม่กว่า
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
    volumes:
      - ./kafka_data1:/bitnami/kafka

  kafka2:
    image: bitnami/kafka:latest
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
    volumes:
      - ./kafka_data2:/bitnami/kafka

  kafkadrop:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: kafka1:9092,kafka2:9092
    depends_on:
      - kafka1
      - kafka2
